// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArQ7M832JfeZXDohZbV4diMzvlvJX2PTA',
    appId: '1:225502020729:web:19a7b7b96d1cfdebec00a8',
    messagingSenderId: '225502020729',
    projectId: 'imagecompressiontutorial',
    authDomain: 'imagecompressiontutorial.firebaseapp.com',
    storageBucket: 'imagecompressiontutorial.firebasestorage.app',
    measurementId: 'G-GV8M5R5TZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHMjqkH0_XPihZtBLF6c1zb56lD4bp_ho',
    appId: '1:225502020729:android:40e457399f4c4cf0ec00a8',
    messagingSenderId: '225502020729',
    projectId: 'imagecompressiontutorial',
    storageBucket: 'imagecompressiontutorial.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHZ7Xxsq6Y4A5mD6epW2q9bNn0vC8v04M',
    appId: '1:225502020729:ios:56a5f45f78cef718ec00a8',
    messagingSenderId: '225502020729',
    projectId: 'imagecompressiontutorial',
    storageBucket: 'imagecompressiontutorial.firebasestorage.app',
    iosBundleId: 'com.yt.imageCompression',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHZ7Xxsq6Y4A5mD6epW2q9bNn0vC8v04M',
    appId: '1:225502020729:ios:56a5f45f78cef718ec00a8',
    messagingSenderId: '225502020729',
    projectId: 'imagecompressiontutorial',
    storageBucket: 'imagecompressiontutorial.firebasestorage.app',
    iosBundleId: 'com.yt.imageCompression',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArQ7M832JfeZXDohZbV4diMzvlvJX2PTA',
    appId: '1:225502020729:web:c94c5fc0a5e74be9ec00a8',
    messagingSenderId: '225502020729',
    projectId: 'imagecompressiontutorial',
    authDomain: 'imagecompressiontutorial.firebaseapp.com',
    storageBucket: 'imagecompressiontutorial.firebasestorage.app',
    measurementId: 'G-5S10E2XP2H',
  );
}
